// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_content: dynamic(() => import("./BlogContent")),
  blog_hero: dynamic(() => import("./BlogHero")),
  hero: dynamic(() => import("./Hero")),
  marquee: dynamic(() => import("./Marquee")),
  rich_text: dynamic(() => import("./RichText")),
};
