// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  marquee: dynamic(() => import("./Marquee")),
  rich_text: dynamic(() => import("./RichText")),
};
